project:
  type: website
  output-dir: docs

website:
  title: "AP2025"
  navbar:
    right:
      - icon: github    
        href: https://github.com/guebin/AP2025
      - icon: youtube
        href: https://www.youtube.com/channel/UCQk9RyBNgXc7ORIsYlOfQrg/playlists?view=50&sort=dd&shelf_id=2
format:
  html:
    theme: cosmo
    # number-sections: true
    number-sections: false
    # number-depth: 3  # h4(####)부터는 넘버링 제거
    css: styles.css
    toc: true
    toc-location: right
    highlight-style: github
    toc-depth: 3
  revealjs:
    output-file: slides.html
    output-dir: docs/slides
    theme: simple
    transition: slide
    background-transition: fade
    incremental: true