---
title: 04wk - 시그마필드 (1)
author: 최규빈
date: 09/23/2025
format:
  revealjs:
    smaller: true
---


### 강의영상 

{{<video https://youtu.be/playlist?list=PLQqh36zP38-wv9meH5OK3wrYO0lwE98pT&si=dMKhFHlMQh_b68Fh >}}

---

### 셀 수 있는

`-` 셀 수 있는 집합과 셀 수 없는 집합. 

- countable: finite, countable many
- uncountable: uncountable many 

---

`-` 예시1: countable set, uncountable set 

- $\{1,2,3,4,5\}$는 셀 수 있는 집합이다. 
- $\mathbb{N}$은 셀 수 있는 집합이다. 
- $\mathbb{Z}$는 셀 수 있는 집합이다. 
- $\mathbb{Q}$는 셀 수 있는 집합이다. 
- $\mathbb{R}$은 셀 수 없는 집합이다. 

---

`-` 예시2: countable sum: 아래는 모두 countable sum을 의미한다. 

- $\sum_{i=1}^{n}a_i$.
- $\sum_{i \in I} a_i$, where $I=\{1,2,3,\dots,10\}$.
- $\sum_{i=1}^{\infty} a_i$, $\sum_{i=0}^{\infty} a_i$.
- $\sum_{i \in \mathbb{N}}a_i$.
- $\sum_{x \in \mathbb{Q}}\lambda(\{x\})$, where $\lambda$ is Lebesgue measure

---

`-` 예시3: countable union: 아래는 countable union을 의미한다. 

- $\cup_{i=1}^n A_i$
- $\cup_{i=1}^{\infty} A_i$
- $\cup_{x \in \mathbb{Q}} \{x\}$

---

`-` 예시4: 아래는 uncountable sum을 의미한다. 

- $\sum_{x \in [0,1]}\lambda(\{x\})$, where $\lambda$ is Lebesgue measure

`-` 예시5: 아래는 uncountable union을 의미한다. 

- $\cup_{x \in [0,1]} \{x\}$

---

### 여러가지 집합

`-` 가산집합 (finite, 셀 수 있는 무한)

|집합|카디널리티|분류|르벡메져|
|:-:|:-:|:-:|:-:|
|$\{1,2,3\}$|3|가산집합|0|
|$\mathbb{N}$|$\aleph_0$|가산집합|0|
|$\mathbb{Z}$|$\aleph_0$|가산집합|0|
|$\mathbb{Q}$|$\aleph_0$|가산집합|0|
|$[0,1]\cap \mathbb{Q}$|$\aleph_0$|가산집합|0|

---

`-` 비가산집합 (셀 수 없는 무한)

|집합|카디널리티|분류|르벡메져|
|:-:|:-:|:-:|:-:|
|$[0,1]$|$\aleph_1$|비가산집합|1|
|$[0,1]\cup \mathbb{Q}$|$\aleph_1$|비가산집합|1|
|$[0,1]\cap \mathbb{Q}^c$|$\aleph_1$|비가산집합|1|
|$[0,\infty)$|$\aleph_1$|비가산집합|$\infty$|

---

`-` 특이한 비가산집합 

|집합|카디널리티|분류|르벡메져|
|:-:|:-:|:-:|:-:|
|칸토어집합|$\aleph_1$|비가산집합|0|
|비탈리집합|$\aleph_1$|비가산집합|NA|

---

### 지금까지의 스토리 

`-` 지금까지의 이야기. (01wk)

- 우리가 원래 원했던 것은 **$\Omega=[0,1]$^[원래는 $\Omega=[0,2\pi)$의 였지만] 의 모든 부분집합에 대해서 확률(=길이)을 "무모순"으로 정의** 하는 것이었다.
- **$\Omega=[0,1]$ 의 모든 부분집합에 대해서 확률(=길이)을 "무모순"으로 정의**하는게 엄청 쉬운일 인줄 알았는데 사실은 그렇지가 않았다. 확률(=길이)을 정의하는건 매우 까다로운 일이었다. 
- 이러한 까다로움을 해결하기 위해서는 "르벡메져"라는 새로운 도구를 사용해야 한다고 했다.

---

`-` 지금가지의 이야기 (02wk,03wk)

- 그런데 르벡메저는 매우 비 직관적인 길이측정방식을 가지고 있었다. 구체적으로 구간 $[0,1]$의 모든 유리수 집합의 길이는 0이지만 구간 $[0,1]$의 모든 무리수 집합의 길이는 1이라는 주장을 하였다. 
- 이는 유리수 집합의 원소수와 무리수 집합의 원소수는 같은 무한이지만 계급이 다르다는 사고방식을 기저에 깔고 있는데 이를 납득하기 위한 최소한의 노력으로 "셀 수 있는 무한"과 "셀 수 없는 무한"의 개념을 공부했다.

---

`-` 우리의 기대

- 우리가 기대한 것: 카디널리티 이해 $\to$ 르벡메저 이해 $\to$ $[0,1]$의 모든 부분집합의 길이를 무모순으로 정의 $\to$ 모든 $\Omega$에 대하여 확률을 무모순으로 정의
- 충격적인 사실: 하지만 르벡메져를 통해서도 $\Omega=[0,1]$의 부분집합중 길이를 잴 수 없는 집합인 비탈리 집합이 존재함이 밝혀졌다. (<https://ko.wikipedia.org/wiki/비탈리_집합>) 즉 르벡메저를 써도 $\Omega=[0,1]$의 모든 부분집합의 확률(=길이)을 모순없이 재는것은 불가능하다.

---

> 그런데, 굳이 비탈리 집합같은곳에서까지 확률(=길이)을 재야하나??

---

`-` 오늘의 이야기 

- $\Omega$의 모든 부분집합에 대해서 확률을 무모순으로 정의하는 일은 포기하자. 
- 대신 $\Omega$의 부분집합 중 확률을 잴 수 있는 집합들에 대해서만 확률을 무모순으로 정의하자. 

---

### 시그마필드 (1)

`-` 목표: $\Omega$의 부분집합 중 확률,길이 등을 "잴 수 있는 집합들의 모임" 이라는 개념을 수학적으로 정의하자. 

`-` 기호에 대한 약속: $\Omega$의 부분집합 중 "잴 수 있는 집합들의 모임"을 일단 기호로 ${\cal F}$ 라 하자. 

---

`-` 당연한 전제: 우리가 정의한 확률은 당연히 확률의 공리를 따라야 한다. 즉 아래가 성립해야 한다. (<https://ko.wikipedia.org/wiki/확률의_공리>)

1. 모든 확률은 0과 1사이의 값이다. 
2. 전체사건 $\Omega$가 발생할 확률은 1이다. (확률의 총합은 1이다)
3. $B_1,B_2,\dots$가 서로소라면 $\mathbb{P}(\cup_{i=1}^{\infty}B_i)=\sum_{i=1}^{\infty}\mathbb{P}(B_i)$가 성립한다. 

---

**`# 예제1`** -- 잴 수 있는 집합의 모임

$\Omega=\{H,T\}$ 라고 하자. 이제 아래와 같은 집합들을 생각하자. $$\emptyset, \{H\}, \{T\}, \Omega$$ 이 집합들은 모두 확률을 모순없이 정의할 수 있는 집합들인가? 

---

(해설)

우리는 이미 이전의 예제에서 $\emptyset$, $\{H\}$, $\{T\}$, $\Omega$ 의 확률을 모순없이 정의할 수 있다는 사실을 논의한 바 있다. 따라서 잴 수 있는 집합들의 묶음 ${\cal F}$을 아래와 같이 정의한다면 묶음 ${\cal F}$가 합리적일 것이다. $${\cal F}=\big\{\emptyset, \{H\}, \{T\}, \Omega\big\}$$ 

`#`

---

> 이때 ${\cal F}$는 집합들의 집합인데, 이러한 집합을 collection 이라고 한다. 

---

**`# 예제2`** -- 집합 $A$의 확률값을 잴 수 있다면, 집합 $A^c$의 확률값도 잴 수 있어~

$\Omega=\{H,T\}$라고 하자. ${\cal F}$을 아래와 같이 정의한다면 묶음 ${\cal F}$는 합리적이지 않다. $${\cal F}=\big\{\emptyset, \{H\}, \Omega\big\}$$ 

---

(해설1) -- 상식에 호소하는 해설

이러한 묶음이 의미하는건 "앞면이 나올 확률은 모순없이 정의할 수 있지만, 뒷면이 나오는 확률은 모순없이 정의하는게 불가능해~" 라는 뜻이다. 그런데 뒷면이 나올 확률은 "1-앞면이 나올 확률" 로 모순없이 정의할 수 있으므로 "앞면
이 나올 확률이 모순없이 정의되면서" 동시에 "뒷면이 나올 확률이 모순없이 정의되지 않는" 상황은 없다. 

---

(해설2) -- 공리에 의한 해설

`-` $\Omega$는 잴 수 있는 집합이다. (왜냐하면 $\Omega \in {\cal F}$ 라고 하였으므로) 따라서 $\mathbb{P}(\Omega)$의 값은 모순없이 정의됨을 알 수 있다. 그런데 확률의 공리2에 의하여 $\mathbb{P}(\Omega)$의 값은 1임을 알 수 있다. 

`-` 한편 $\{H\}$ 역시 잴 수 있는 집합이다. (왜냐하면 $\{H\} \in {\cal F}$ 라고 하였으므로) 따라서 $\mathbb{P}(\{H\})$의 값은 모순없이 정의됨을 알 수 있다. 이 값을 편의상 $p$ 라고 가정하자. 확률의 공리1에 의하여 $0\leq p \leq 1$ 임을 알 수 있다. 

---

`-` 아래의 수식을 관찰하자.

$$\Omega = \{H\} \uplus \{T\} \Rightarrow \mathbb{P}(\Omega) = \mathbb{P}(\{H\}) + \mathbb{P}(\{T\})$$

수식에서 왼쪽이 성립하는 이유는 확률과 상관없는 집합이론이고 $\Rightarrow$ 가 성립하는 이유는 확률의공리3에 의해서 이다. 따라서 

$$\mathbb{P}(\{T\})=\mathbb{P}(\Omega)-\mathbb{P}(\{H\})=1-p$$

로 "모순없이" 정의될 수 있어야 한다.


---

 즉 $\{T\}$는 잴 수 있는 집합이어야 한다. 그런데 $\{T\}$는 ${\cal F}$의 원소가 아니므로 묶음 ${\cal F}$는 합리적이지 않다. 

`#`

---

::: {.callout-note}

**[여집합에 닫힘]**: 집합 $A$의 확률값을 잴 수 있다면, 집합 $A^c$의 확률값도 잴 수 있어야 한다. 즉 아래가 성립해야한다. $$\forall A \subset \Omega:~ A \in {\cal F} \Rightarrow A^c \in {\cal F}$$ 이를 좀 더 간단하게는 아래와 같이 쓸 수 있다. $$A \in {\cal F} \Rightarrow A^c \in {\cal F}$$ 
왜냐하면 ${\cal F}$의 원소라는 점은 이미 $\Omega$의 부분집합임을 암시하고 있으므로 $A \subset \Omega$ 라는 조건은 생략가능하기 때문이다. 

:::

---

> 아이디어: ${\cal F}$ 라는 것은 확률값을 잴 수 있는 집합과 확률값을 잴 수 없는 집합을 동시에 정의하고 있음을 주목하자. 즉 ${\cal F}=\big\{\emptyset, \{H\}, \Omega\big\}$ 일때 $\{H\}$가 확률값을 잴 수 있는 집합이라는 사실에만 초점을 맞추지 말고 $\{T\}$가 확률값을 잴 수 없는 집합이라는 사실에도 초점을 맞추어야 한다. 

---

**`# 예제3`** -- 전체집합에 대한 확률값을 잴 수 있다면, 공집합에 대한 확률도 잴 수 있어.

$\Omega=\{H,T\}$라고 하자. ${\cal F}$를 아래와 같이 정의한다면 묶음 ${\cal F}$는 합리적이지 않다. $${\cal F}=\big\{ \{H\}, \{T\}, \Omega\big\}$$ 

---

(해설)

전체집합의 확률은 $\mathbb{P}(\Omega)=1$로 정의할 수 있다. 그런데 전체집합의 여집합인 공집합의 확률을 정의할 수 없는건 말이 안되므로 공집합은 $\cal F$에 포함되어야 한다. 

`#`

> 예전기억: 왜 $\mathbb{P}(\emptyset)=0$ 인지 이제 알겠죠?

---

`# 예제4` -- 원소의 수가 유한한 경우 ${\cal F}=2^\Omega$은 잴 수 있는 집합의 모임이야. 

$\Omega=\{1,2,3,4,5,6\}$이라고 하자. ${\cal F}$을 아래와 같이 정의한다고 하자. 이러한 묶음은 ${\cal F}$은 합리적이다. 

$$\begin{align*}
{\cal F}&=\text{all subset of $\Omega$}= 2^\Omega \\
&= \big\{ \emptyset, \{1\}, \dots, \{6\}, \dots, \{1,2,3,4,5\}, \dots \Omega\big\}
\end{align*}$$ 

---

(해설)

$\Omega$의 모든 부분집합에 대하여 확률을 모순없이 정의할 수 있다. 예를들면 

- $P(\Omega)=1$, $P(\emptyset)=0$ 
- $P(\{1\})=\frac{1}{6}$
- $P(\{1,2,4\})=\frac{3}{6}$
- $P(\{2,3,4,5,6\})=\frac{5}{6}$
- $\dots$

이런식으로 정의할 수 있다. 

---

**`# 에제5`** -- 동일한 $\Omega$에 대하여 확률값을 잴 수 있는 집합의 모임 ${\cal F}$는 유니크하지 않음. 

$\Omega=\{1,2,3,4,5,6\}$이라고 하자. ${\cal F}$을 아래와 같이 정의한다고 하자. 이러한 묶음 ${\cal F}$는 합리적이다. $${\cal F}=\big\{\emptyset, \{6\}, \{1,2,3,4,5\},\Omega \big\}$$ 

---

(해설) 

어떠한 특수한 상황을 가정하자. 주사위를 던져야하는데 6이 나오면 살수 있고 6이 나오지 않으면 죽는다고 하자. 따라서 던지는 사람 입장에서는 주사위를 던져서 6이 나오는지 안나오는지만 관심있을 것이다. 이 사람의 머리속에서 순간적으로 떠오르는 확률들은 다음과 같다.


- 살수있다 $\to$ 1/6 
- 죽는다 $\to$ 5/6 
- 살거나 죽는다 $\to$ 1 
- 살지도 죽지도 않는다 $\to$ 0 

---




이러한 확률은 합리적이다. 즉 아래의 집합들만 확률을 정의한다고 해도, 확률을 잘 정의할 수 있을 것 같다. 

$$\emptyset, \{6\}, \{1,2,3,4,5\}, \Omega$$

`#`

---

**`# 예제6`** 

$\Omega=\{1,2,3,4,5,6\}$이라고 하자. ${\cal F}$을 아래와 같이 정의한다고 하자. 이러한 묶음 ${\cal F}$는 합리적이다. 

$${\cal F}=\big\{\emptyset, \{1,3,5\}, \{2,4,6\},\Omega \big\}$$

---

(해설) 

전체사건을 "주사위를 던져서 짝이 나오는 사건", "주사위를 던져서 홀이 나오는 사건" 정도만 구분하겠다는 의미

`#`

---

**`# 예제7`** 

$\Omega=\{1,2,3,4,5,6\}$이라고 하자. ${\cal F}$을 아래와 같이 정의한다고 하자. 이러한 묶음 ${\cal F}$는 합리적이지 않다. $${\cal F}=\big\{\emptyset, \{1,3,5\}, \Omega \big\}$$ 

---

(해설) 

"주사위를 던져서 홀수가 나올 사건"에 대한 확률을 정의할 수 있는데, 짝수가 나올 사건에 대한 확률을 정의할 수 없다는건 말이 안되는 소리임. 

`#`

---

**`# 예제8`**

$\Omega=\{1,2,3,4\}$이라고 하자. 어떠한 필요에 따라서 1이 나올 확률과 2가 나올 확률에만 관심이 있고 나머지는 별로 관심이 없다고 하자. 그래서 ${\cal F}$ 를 아래와 같이 정의했다고 하자. 이러한 묶음 ${\cal F}$ 는 합리적이지 않다. $${\cal F}=\{\emptyset, \{1\}, \{2\}, \{2,3,4\}, \{1,3,4\}, \Omega \}$$ 

---

(해설1) 

${\cal F}$ 는 전체집합과 공집합을 포함하고 여집합에 닫혀있으므로 언뜻 생각해보면 합리적인듯 보이지만 그렇지 않다. 왜냐하면 $\{1,2\}$이 빠졌기 때문이다. 1이 나올 확률 $\mathbb{P}(\{1\})$와 2가 나올 확률 $\mathbb{P}(\{2\})$를 각각 정의할 수 있는데, 1 또는 2가 나올 확률 $\mathbb{P}(\{1,2\})$을 정의할 때 모순이 발생한다는 것은 합리적이지 못하다. 왜냐하면 $\{1\} \cap \{2\} = \emptyset$ 이므로 

$$\mathbb{P}(\{1\} \uplus \{2\})=\mathbb{P}(\{1\}) + \mathbb{P}(\{2\})$$

와 같이 정의가능하기 때문이다. 

---

따라서 집합이 아래와 같이 수정되어야 한다. 

$${\cal F}=\{\emptyset, \{1\}, \{2\}, \{2,3,4\}, \{1,3,4\}, \Omega, \{1,2\}, \{3,4\} \}$$

---

(해설2) 

아래를 관찰하자. 

$$\{2\} \uplus \{3,4\} =\{2,3,4\}$$

양변에 확률을 취하자. 

$$\mathbb{P}(\{2\}) + \mathbb{P}(\{3,4\}) = \mathbb{P}(\{2,3,4\})$$

그런데 여기에서 $\mathbb{P}(\{2\})$와 $\mathbb{P}(\{2,3,4\})$는 정의가능한데, $\mathbb{P}(\{3,4\})$는 정의할 수 없다는 사실이 말이 안된다.

---


따라서 ${\cal F}$를 아래와 같이 수정해야 한다. 

$${\cal F}=\{\emptyset, \{1\}, \{2\}, \{2,3,4\}, \{1,3,4\}, \Omega, \{3,4\}, \{1,2\} \}$$

`#`

---

::: {.callout-note}

해설2에 대한 논의를 일반화 하면 $$A\subset B  \Rightarrow B = A \uplus (B-A) \Rightarrow \mathbb{P}(B) = \mathbb{P}(A) +\mathbb{P}(B-A)$$이므로, $A,B$ 가 확률값을 잴 수 있는 집합이라면 $B-A$ 역시 확률값을 잴 수 있는 집합이어야 한다고 결론지을 수 있다. 


:::

---

::: {.callout-note}

**[$\uplus$에 닫힘]**: 서로소인 두 집합 $A,B$ 에서 확률값을 잴 수 있다면, 당연히 $A \uplus B$ 에서도 확률값을 잴 수 있어야 한다. 즉 아래가 성리해야한다. 

$$A \in {\cal F}, B \in {\cal F} \text{ and } A\cap B = \emptyset \quad \Longrightarrow \quad A \uplus B~ \in~ {\cal F}$$

:::

---

::: {.callout-note}

**[포함관계에 있는 집합의 차집합에 닫힘]**: 포함관계에 있는 두 집합 $A\subset B$ 에서 모두 확률값을 잴 수 있다면, 당연히 $B-A$ 에서도 확률값을 잴 수 있어야 한다. 즉 아래가 성리해야한다. $$A \in {\cal F}, B \in {\cal F} \text{ and } A \subset B  \quad \Longrightarrow \quad B-A ~ \in {\cal F}$$ 

:::

