---
title: 05wk - 시그마필드 (2)
author: 최규빈
date: 10/09/2025
format:
  revealjs:
    smaller: true
---


### 강의영상 

{{<video xxxx >}}

---

### 시그마필드 (2)

**`# 예제1`** 

$\Omega=\{1,2,3,4\}$이라고 하자. 내가 관심이 있는 확률은 $\mathbb{P}(\{1\})$, $\mathbb{P}(\{2\})$ 밖에 없다고 하자. 이러한 확률들이 무모순으로 정의되기 위한 최소한의 ${\cal F}$ 를 정의하라. 

(풀이) -- 좀 귀찮네..?

0차수정: ${\cal A} = \big\{\{1\}, \{2\}\big\}$

1차수정: $\big\{\emptyset, \{1\}, \{2\}, \Omega \big\}$

2차수정: $\big\{\emptyset, \{1\}, \{2\}, \{2,3,4\}, \{1,3,4\}, \Omega \big\}$

3차수정: $\big\{\emptyset, \{1\}, \{2\}, \{2,3,4\}, \{1,3,4\}, \Omega, \{1,2\}, \{3,4\} \big\}$

---

(생각) -- $\sigma({\cal A})$의 도입

- 사실 우리가 관심 있는건 ${\cal A} = \{ \{1\}, \{2\} \}$이므로, 우리는 $\mathbb{P}(\{1\})$와 $\mathbb{P}(\{2\})$의 값에만 사실 관심이 있었음. 
- 그런데 $\mathbb{P}(\{1\})$와 $\mathbb{P}(\{2\})$를 합리적으로 정의하기 위해서 필연적으로 발생하는 어떠한 집합들을 모두 생각해야함. 
- 이건 매우 피곤하고 귀찮은 일임. 
- 그래서 "아 모르겠고, $\{1\}$ 와 $\{2\}$ 를 포함하고 확률의 뜻에 모순되지 않게 만드는 최소한의 ${\cal F}$ 가 있을텐데, 거기서만 확률을 정의할래!" 라고 쉽게 생각하고 싶은 사람들이 생김. 
- 그러한 공간을 $\sigma({\cal A})$ 라는 기호로 약속하고 smallest $\sigma$-field containing ${\cal A}$ 라는 용어로 부름. 

`#`

---

**`# 예제2`** 

$\Omega=[0,1)$이라고 하자. 집합 $\mathbb{Q}$를 구간 $[0,1)$에 포함된 모든 유리수의 집합이라고 하자. ${\cal A} = \{\{x\}: x\in \mathbb{Q}\}$ 이라고 하자. 아래가 성립할까? $$\mathbb{Q} \in \sigma({\cal A})$$ 즉 구간 $[0,1)$에서의 유리수를 한점씩을 잴 수 있을 때 구간 $[0,1)$의 모든 유리수 집합 역시 잴 수 있어야 할까? 단, 모든 $x \in [0,1)$ 에 대하여 $\mathbb{P}(\{x\})=\lambda(\{x\})$ 라고 하자. (여기에서 $\lambda$는 르벡측도임)

---

(해설) 

`-` 집합 $\{\frac{1}{2}\}$는 잴 수 있고, 집합 $\{\frac{1}{3}\}$ 역시 잴 수 있다. (왜?? $\frac{1}{2}, \frac{1}{3}$은 유리수니까) 그렇다면 집합 $\{\frac{1}{2},\frac{1}{3}\}=\{\frac{1}{2}\} \uplus \{\frac{1}{3}\}$ 역시 잴 수 있어야 하며, $\mathbb{P}(\{\frac{1}{2}\} \uplus \{\frac{1}{3}\})=0$ 이다. 왜냐하면 확률의 공리에 의하여 아래식이 성립하기 때문이다. 



$$\mathbb{P}(A_1 \uplus A_2)=  \mathbb{P}(A_1) + \mathbb{P}(A_2)$$

비슷한 논리로 집합 $\{\frac{1}{2},\frac{1}{3},\dots \}$ 역시 잴 수 있어야 한다. 왜냐하면 확률의 공리에 의하여 아래식이 성립하기 때문이다. 

$$\mathbb{P}(\uplus_{n=1}^{\infty} A_n) =  \sum_{n=1}^{\infty}\mathbb{P}(A_n)$$

---

`-` 집합 $\mathbb{Q}$ 는 잴 수 있을까? $\mathbb{Q}$ 의 카니널리티는 자연수의 카디널리티와 같으므로 $\mathbb{N} \to \mathbb{Q}$ 인 전단사함수 $f$가 존재하며, 따라서 $$\mathbb{Q} = \{f(1),f(2),\dots, \} = \uplus_{n=1}^{\infty}\{ f(n) \}$$ 와 같이 쓸 수 있다. 확률의 공리에 의하여 아래식이 성립한다. $$\mathbb{P}(\mathbb{Q}) = \sum_{n=1}^{\infty} \mathbb{P}(\{f(n)\})$$
우변의 값은 (무모순으로) 0으로 정의된다. 따라서 좌변 $\mathbb{P}(\mathbb{Q})$ 역시 무모순으로 정의되어야 하며 그 값은 0이다. 

`-` 즉 $$\mathbb{Q} \in \sigma({\cal A})$$ 이어야 한다. 

---

::: {.callout-note}

**[$\uplus_{n=1}^{\infty}$에 닫힘]**: 서로소인 집합들 $A_1,A_2,\dots$ 에서 확률값을 잴 수 있다면, $A=\uplus_{n=1}^{\infty} A_n$ 에서도 확률값을 잴 수 있어야 한다. 즉 아래가 성리해야한다. $$\begin{cases} \forall n \in \mathbb{N}: A_n \in {\cal F} \\ \forall {m,k} \in \mathbb{N}, m\neq k:~  A_m \cap A_k = \emptyset\end{cases} \quad \Rightarrow \quad \uplus_{n=1}^{\infty} A_n \in {\cal F}$$

:::

`#`

---

**`# 예제3`** 

$\Omega=[0,1)$ 이라고 하자. 집합 $\mathbb{Q}$ 를 구간 $[0,1)$에 포함된 모든 유리수의 집합이라고 하자. ${\cal A} = \{\{x\}: x\in \mathbb{Q}\}$ 이라고 하자. 아래가 성립할까?

$$\mathbb{Q}^c \in \sigma({\cal A})$$

단, 여기에서 $\mathbb{Q}^c$ 는 구간 $[0,1)$에 포함된 모든 무리수의 집합이다. 

---

(해설)

$\mathbb{Q} \in \sigma({\cal A})$ 이므로 $\mathbb{Q}^c\in \sigma({\cal A})$ 이어야 한다. $\mathbb{P}(\mathbb{Q})=0$ 이므로, $\mathbb{P}(\Omega - \mathbb{Q})=1$ 이다. 

> $\mathbb{Q}^{c}=\uplus_{x \in \mathbb{Q}^c} \{x\}$ 의 꼴로 표현될 수 있지만, $\mathbb{Q}^{c}=\uplus_{x \in \mathbb{Q}^c} \{x\}=\uplus_{n=1}^{\infty}\{x_n\}$ 와 같이 표현할 수 없으므로 $\mathbb{P}(\mathbb{Q}^{c})=\sum_{x \in \mathbb{Q}^c}\mathbb{P}(\{x\})$ 와 같이 쓸 수 없음을 주의하라. (똑똑한 초등학생 논리의 완벽한 카운터)

`#`

---

**`# 예제3`** 

$\Omega=\{1,2,3,4,5,6\}$ 이라고 하자. ${\cal F}=\emptyset$ 와 같이 정의한다면 합리적인가? 

(풀이) 

쉽게말하면 잴 수 있는 집합이 없다는 의미 $\Rightarrow$ 일반적인 상식 (혹은 확률의 공리)에 호소하며 합리적이지 혹은 비합리적인지 따지기 어려움 $\Rightarrow$ ${\cal F}\neq \emptyset$ 이라고 "약속"하자.

`#`

---

**`# 지금까지의 예제를 풀며 얻은 결론`**

지금까지의 조건을 종합하면, $\Omega$의 부분집합 중 잴 수 있는 집합들의 모임 ${\cal F}$은 아래의 조건을 충족해야할 것 같다. 

`1`. 잴 수 있는 집합의 모임 ${\cal F}$은 공집합이 아님 $${\cal F}\neq \emptyset$$

`2`. 잴 수 있는 집합의 모임 ${\cal F}$에는 항상 전체집합이 있어야함 (공리1) $$\Omega \in {\cal F}$$


`3`. 잴 수 있는 집합의 모임 ${\cal F}$는 여집합 연산에 닫혀있음. (공리3 파생) $$A \in {\cal F} \Rightarrow A^c \in {\cal F}$$ 



---



`4`. 잴 수 있는 집합의 모임 ${\cal F}$는 유한 서로소 합집합 연산에 닫혀있음. (공리3) $$\begin{cases} A \in {\cal F}, B \in {\cal F} \\ A\cap B = \emptyset\end{cases} \Rightarrow A \uplus B~ \in~ {\cal F}$$

`5`. 잴 수 있는 집합의 모임 ${\cal F}$는 포함관계가 있는 차집합 연산에 닫혀있음. (공리3 파생) $$\begin{cases}A \in {\cal F}, B \in {\cal F} \\  A \subset B \end{cases} \Rightarrow B-A ~ \in~ {\cal F}$$

`6`. 잴 수 있는 집합의 모임 ${\cal F}$는 가산 서로소 합집합 연산에 닫혀있음. (공리3) $$\begin{cases} \forall n \in \mathbb{N}: A_n \in {\cal F} \\ \forall {m,k} \in \mathbb{N}, m\neq k:~  A_m \cap A_k = \emptyset\end{cases} \Rightarrow  \uplus_{n=1}^{\infty} A_n \in {\cal F}$$

`#`

---

**`# 조건의 정리`** 

위의 6개의 조건은 아래의 3가지 조건으로 정리가능하다. 

`1`. 전체집합을 포함 ($\Omega \in {\cal F}$)

`2`. 여집합에 닫힘 ($A \in {\cal F} \Rightarrow A^c \in {\cal F}$)

`3`. 가산서로소합집합에 닫힘 $$\begin{cases} \forall n \in \mathbb{N}: A_n \in {\cal F} \\ \forall {m,k} \in \mathbb{N}, m\neq k:~  A_m \cap A_k = \emptyset\end{cases} \Rightarrow  \uplus_{n=1}^{\infty} A_n \in {\cal F}$$

`#`

---

**`# 람다시스템`**

$\Omega$의 부분집합중 잴 수 있는 집합의 모임 ${\cal F}$ 는 아래의 조건 `1`~ `3`을 만족하는 집합의 집합 (collection) 이라고 정의하면 어떨까?? (그럴싸하지만, 하나의 조건이 더 필요하다.)

`1`. 전체집합을 포함 ($\Omega \in {\cal F}$)

`2`. 여집합에 닫힘 ($A \in {\cal F} \Rightarrow A^c \in {\cal F}$)

`3`. 가산서로소합집합에 닫힘 $$\begin{cases} \forall n \in \mathbb{N}: A_n \in {\cal F} \\ \forall {m,k} \in \mathbb{N}, m\neq k:~  A_m \cap A_k = \emptyset\end{cases} \Rightarrow  \uplus_{n=1}^{\infty} A_n \in {\cal F}$$

`#` 

---

**`# 예제4`** 

$\Omega=\{1,2,3,4\}$라고 하자. 아래와 같은 잴 수 있는 집합들의 모임은 합리적일까?

$$\big\{\emptyset, \{1,2\}, \{1,3\}, \{1,4\},\{2,3\},\{2,4\},\{3,4\}, \Omega\big\}$$

혹시 $\{1,2\} \cap \{1,3\} = \{1\}$ 와 같은건 잴 수 있다고 보는게 더 합리적이지 않을까? 

`(해설?)` 

집합 $A$와 $B$에 대한 확률값을 매길 수 있다면 $\mathbb{P}(A \cap B)$를 정의할 수 있어야 할까? 주어진 ${\cal F}$는 아래의 조건을 만족한다. 

- 전체집합을 포함
- 여집합에 닫힘 
- 가상가법성 만족 

여기에 "교집합에 닫혀있음"이라는 조건도 추가적으로 필요할까? 

---

사실 딱히 그러한 조건이 필요해보이진 않는다. 아래와 같이 확률을 정의한다고 가정하자. 

- $\mathbb{P}(\emptyset)=0$, $\mathbb{P}(\Omega)=1$
- $\mathbb{P}(\{1,2\})=\dots=\mathbb{P}(\{3,4\})=\frac{1}{2}$

이러한 확률정의가 어떠한 공리를 위배하는가? 위배하는 것이 없다. 

> 합의: 그렇지만.. 그냥 $A,B$를 잴 수 있다면 $A \cap B$ 도 잴 수 있다고 합의하시죠..

`#`

---

**`# 조건의정리 (교집합을 추가하면)`**

두 집합 $A$, $B$에 대한 확률을 무모순으로 정의가능하다면 그것의 교집합인 $A\cap B$에 대하여서도 확률값을 무모순으로 정의가능하다고 가정하자. 즉 $\Omega$의 부분집합중 잴 수 있는 집합의 모임 ${\cal F}$ 는 아래의 조건 `1`~ `4`을 만족하는 집합의 집합 (collection) 이라고 정의하자. 

`1`. 전체집합을 포함 ($\Omega \in {\cal F}$)

`2`. 여집합에 닫힘 ($A \in {\cal F} \Rightarrow A^c \in {\cal F}$)

`3`. 가산서로소합집합에 닫힘 $$\begin{cases} \forall n \in \mathbb{N}: A_n \in {\cal F} \\ \forall {m,k} \in \mathbb{N}, m\neq k:~  A_m \cap A_k = \emptyset\end{cases} \Rightarrow  \uplus_{n=1}^{\infty} A_n \in {\cal F}$$

`4`. 교집합에 닫힘 ($A,B \in {\cal F} \Rightarrow A \cap B \in {\cal F}$)

---

그런데 조건`3` 가산서로소합집합에 닫힘과 `4` 교집합에 닫힘을 이용하면 아래와 같은 조건 `5`를 유추할 수 있다. 

`5`. 가산합집합에 닫힘 

$$\big(\forall n \in \mathbb{N}: A_n \in {\cal F} \big) \Rightarrow \cup_{n=1}^{\infty} A_n \in~ {\cal F}$$

---

`# 조건의 간소화` 

`1`. 전체집합을 포함 ($\Omega \in {\cal F}$)

`2`. 여집합에 닫힘 ($A \in {\cal F} \Rightarrow A^c \in {\cal F}$)

`3`. 가산서로소합집합에 닫힘 

`4`. 교집합에 닫힘 ($A,B \in {\cal F} \Rightarrow A \cap B \in {\cal F}$)

`5`. 가산합집합에 닫힘 

- 조건 1-4를 지키기 위해서는 조건 1-5를 지키면 된다. 
- 그런데 조건5가 지켜지면 조건3은 자동으로 지켜지므로 조건 1-5를 지키기 위해서는 조건 1,2,4,5만 지키면 된다. (즉 조건3을 지울 수 있다) 
- 그런데 조건5와 조건2가 지켜지면 조건4가 자동으로 지켜지므로, 조건 1,2,4,5를 지키기 위해서는 조건 1,2,5만 지키면된다. (즉 조건 4를 지울 수 있다) 
- 결론적으로 조건 1-4를 지키기 위해서는 조건 1,2,5만 지키면 된다.

---

**`# 정의: 시그마필드`**

$\Omega$의 부분집합중 아래의 조건`1`~ `3`을 만족하는 집합의 집합 (collection) ${\cal F}$를 "$\Omega$에 대한 시그마필드"라고 한다. 

`1`. 전체집합을 포함 ($\Omega \in {\cal F}$)

`2`. 여집합에 닫힘 ($A \in {\cal F} \Rightarrow A^c \in {\cal F}$)

`3`. 가산합집합에 닫힘 

$$\forall n \in \mathbb{N}: A_n \in {\cal F} \Rightarrow \cup_{n=1}^{\infty} A_n \in~ {\cal F}$$

그리고 ${\cal F}$의 원소를 ${\cal F}$-measurable set 이라고 한다. 

`#`

---

`-` 참고1: 시그마필드는 $\Omega$ 없이 단독으로 정의되지 않는다. 즉

$${\cal F}=\{\emptyset, \{H\}, \{T\}, \{H,T\}\}$$

는 단지 그냥 시그마필드라고 언급하기 보다 $\Omega=\{H,T\}$에 대한 시그마필드라고 해야 정확한 표현이다.

`-` 참고2: 참고1에 따라서 ${\cal F}$ 단독으로 표기하는 것 보다 $\Omega$를 붙여서 $(\Omega,{\cal F})$와 같이 쌍으로 표기하는게 더 합리적이다. 앞으로는 이러한 쌍을 ***measurable space*** 라고 부른다.

`-` 참고3: 보통의 교재(링크)에서는 시그마필드의 정의부터 시작하는 경우가 많다. 

- <https://services.math.duke.edu/~rtd/PTE/PTE5_011119.pdf>
