---
title: 06wk - 측도, 확률 / 르벡메저, 보렐시그마필드
author: 최규빈
date: 10/10/2025
---

### 강의영상

{{<video https://youtu.be/playlist?list=PLQqh36zP38-z9RolzS-23orzufOCzRwXI&si=ktQKgPRGr9wm_Xi4 >}}

------------------------------------------------------------------------

### 측도와 확률측도의 정의

`# 확률의 정의`: 확률은 잴 수 있는 공간 $(\Omega, {\cal F})$이 전제되었을 경우 정의 할 수 있는 일종의 함수 $\mathbb{P}:{\cal F} \to [0,1]$ 이다. $\mathbb{P}$가 확률이라고 불리기 위해서는 아래의 조건을 만족해야 한다.

`1`. 확률값은 음이 될 수 없다. ($\forall A \in {\cal F}:~ \mathbb{P}(A) \geq 0$)

`2`. 전체확률은 항상 1이다. ($\mathbb{P}(\Omega)=1$)

`3`. 가산가법성을 만족한다.

$$\begin{cases} \forall n \in \mathbb{N}: B_n \in {\cal F}  \\ \forall {m,k} \in \mathbb{N}, m\neq k:~  B_m \cap B_k = \emptyset \end{cases} \Rightarrow \mathbb{P}\left(\uplus_{n=1}^{\infty} B_n\right) = \sum_{n=1}^{\infty}\mathbb{P}(B_n)$$

`#`

------------------------------------------------------------------------

`-` 잴 수 있는 집합들의 모임 (=시그마필드), 잴 수 있는 집합 (=시그마필드의 원소), 잴 수 있는 공간 혹은 가측공간의 주어는 확률이 아니라 측도(=measure)이다.

`# measure의 정의`: 측도(measure)는 잴 수 있는 공간 $(\Omega, {\cal F})$가 전제되었을 경우 정의 할 수 있는 일종의 함수 $m: {\cal F} \to [0,\infty]$ 이다. $m$이 메저라고 불리기 위해서는 아래의 조건을 만족해야 한다.

`1`. 메저값은 음이 될 수 없다 ($\forall A \in {\cal F}:~ m(A) \geq 0$)

`2`. 공집합의 측정값은 0이다 ($m(\emptyset)=0$)

`3`. 가산가법성을 만족한다.

$$\begin{cases} \forall n \in \mathbb{N}: B_n \in {\cal F}  \\ \forall {m,k} \in \mathbb{N}, m\neq k:~  B_m \cap B_k = \emptyset \end{cases} \Rightarrow m\left(\uplus_{n=1}^{\infty} B_n\right) = \sum_{n=1}^{\infty}m(B_n)$$

`#`

------------------------------------------------------------------------

`# 예제1` 확률은 메저의 한 종류임을 보여라. 즉 확률의 공리1-3을 만족하면 메저의 공리1-3을 만족함을 보여라.

`# 예제2` 메저의 정의에서 `조건4` $m(\Omega)=1$ 임을 추가하면 확률의 공리1-3이 됨을 보여라.

------------------------------------------------------------------------

### 확률(=확률측도)

`# 예제1` -- 시그마필드에서만 확률정의가능

$\Omega=\{H,T\}$ 라고 하고 ${\cal F}=\{\emptyset, \{H\},\Omega\}$ 이라고 하자. 아래와 같은 함수 $\mathbb{P}$ 를 고려하고 이것을 확률이라고 하자. 이러한 확률은 합리적인가?

-   $\mathbb{P}(\emptyset) = 0$
-   $\mathbb{P}(\{H\}) = \frac{1}{2}$
-   $\mathbb{P}(\Omega) = 1$

(해설) ${\cal F}$는 시그마필드가 아니므로 이 위에서는 애초에 확률을 정의할 수 없음.

> 확률을 잘 정의하기 위해서는 우선 잘 정의된 "잴 수 있는 공간 $(\Omega, {\cal F})$" 가 필요하다.

`#`

------------------------------------------------------------------------

`# 예제2` -- 잘 정의된 확률

$\Omega=\{H,T\}$ 라고 하고 ${\cal F}=2^{\Omega}$ 이다. 아래와 같은 함수 $\mathbb{P}$ 를 고려하고 이를 잴 수 있는 공간 $(\Omega,{\cal F})$ 에서의 확률이라고 하자. 이러한 확률은 합리적인가?

-   $\mathbb{P}(\emptyset) = 0$
-   $\mathbb{P}(\{H\}) = \frac{1}{100}$
-   $\mathbb{P}(\{T\}) = \frac{99}{100}$
-   $\mathbb{P}(\Omega) = 1$

(해설) 합리적임.

`#`

------------------------------------------------------------------------

`# 예제3` -- 확률은 0보다 커야해.

$\Omega=\{H,T\}$ 라고 하고 ${\cal F}=2^{\Omega}$ 이다. 아래와 같은 함수 $\mathbb{P}$ 를 고려하고 이를 잴 수 있는 공간 $(\Omega,{\cal F})$ 에서의 확률이라고 하자. 이러한 확률은 합리적인가?

-   $\mathbb{P}(\emptyset) = 0$
-   $\mathbb{P}(\{H\}) = -\frac{1}{2}$
-   $\mathbb{P}(\{T\}) = \frac{1}{2}$
-   $\mathbb{P}(\Omega) = 1$

(해설) 확률은 음수가 나오면 안되므로 합리적이지 않음.

`#`

------------------------------------------------------------------------

`# 예제4` -- 전체확률은 1이어야 함.

$\Omega=\{H,T\}$ 라고 하고 ${\cal F}=\{\emptyset, \Omega\}$ 이다. 아래와 같은 함수 $\mathbb{P}:{\cal F} \to [0,1]$를 고려하고 이를 잴 수 있는 공간 $(\Omega,{\cal F})$ 에서의 확률이라고 하자. 이러한 확률은 합리적인가?

-   $\mathbb{P}(\emptyset) = 0$
-   $\mathbb{P}(\Omega) = 0.5$

(해설) 전체확률은 1이어야 하므로 합리적이지 않음.

`#`

------------------------------------------------------------------------

`# 예제5` -- 공집합의 확률은 0이어야 함.

$\Omega=\{H,T\}$ 라고 하고 ${\cal F}=\{\emptyset, \Omega\}$ 이다. 아래와 같은 함수 $\mathbb{P}:{\cal F} \to [0,1]$를 고려하고 이를 잴 수 있는 공간 $(\Omega,{\cal F})$ 에서의 확률이라고 하자. 이러한 확률은 합리적인가?

-   $\mathbb{P}(\emptyset) = 0.5$
-   $\mathbb{P}(\Omega) = 1$

(해설) 공집합의 확률은 0이어야 하므로 (왜?) 합리적이지 않음.

`#`

------------------------------------------------------------------------

`# 예제6` -- 서로소인 집합을 합친 확률, 여집합의 확률

$\Omega=\{H,T\}$ 라고 하고 ${\cal F}=\{\emptyset, \{H\}, \{T\}, \Omega\}$ 이다. 아래와 같은 함수 $\mathbb{P}:{\cal F} \to [0,1]$를 고려하고 이를 잴 수 있는 공간 $(\Omega,{\cal F})$ 에서의 확률이라고 하자. 이러한 확률은 합리적인가?

-   $\mathbb{P}(\emptyset) = 0$
-   $\mathbb{P}(\{H\}) = 1/3$
-   $\mathbb{P}(\{T\}) = 1/3$
-   $\mathbb{P}(\Omega) = 1$

(해설) 합리적이지 않음. 왜냐하면

-   $P(\{H\}\cup \{T\})=P(\Omega)=1$
-   $P(\{H\}\cup \{T\})=P(\{H\})+P(\{T\})=2/3$

이므로 모순임.

`#`

---

> 정의역이 시그마필드이고, 확률의 공리1,2,3을 만족하는 경우만 우리는 확률이라 인정하겠다. \<-- 이것만 기억하면 이런식의문제는 계속 풀 수 있음.

---

`# 예제7` -- 포함관계에 있는 집합의 확률

$\Omega=\{1,2,3\}$ 라고 하고 $${\cal F}=\{\emptyset, \{1\}, \{2\}, \{3\}, \{1,2\}, \{1,3\}, \{2,3\}, \Omega\}$$ 라고 하자. 아래와 같은 함수 $\mathbb{P}:{\cal F} \to [0,1]$를 고려하고 이를 잴 수 있는 공간 $(\Omega,{\cal F})$ 에서의 확률이라고 하자.

-   $\mathbb{P}(\emptyset) = 0$
-   $\mathbb{P}(\{1\}) = 1/4$
-   $\mathbb{P}(\{2\}) = 1/4$
-   $\mathbb{P}(\{3\}) = 2/4$
-   $\mathbb{P}(\{1,2\}) = 2/4$
-   $\mathbb{P}(\{1,3\}) = 3/4$
-   $\mathbb{P}(\{2,3\}) = 1/4$
-   $\mathbb{P}(\Omega) = 1$

이러한 확률은 합리적인가?

------------------------------------------------------------------------

(풀이) 합리적이지 않음. 왜냐하면

-   $\mathbb{P}(\{2\}\cup \{3\})=\mathbb{P}(\{2,3\})=1/4$
-   $\mathbb{P}(\{2\}\cup \{3\})=\mathbb{P}(\{2\})+\mathbb{P}(\{3\})=3/4$

이므로 모순임.

`#`

------------------------------------------------------------------------

### 확률측도와 측도의 차이

`# 예제1` -- $|\Omega|<\infty$ 인 경우

$\Omega=\{1,2,3,4,5,6\}$ 라고 하자. 이때 $2^\Omega$는 $\Omega$의 모든 부분집합들의 집합이다. 여기에서 $2^\Omega$는 시그마필드의 정의를 만족하므로 $(\Omega, 2^{\Omega})$ 는 잴 수 있는 공간이 된다.[^1] 이 공간위에서 함수 $\mathbb{P}: 2^{\Omega} \to [0,1]$ 를 아래와 같의 정의하자.

[^1]: 꿀팁: $(\Omega, 2^\Omega)$는 무조건 measurable space가 된다

$$\mathbb{P}(A)=\frac{|A|}{|\Omega|}.$$

이러한 함수 $\mathbb{P}$ 는 (1) 정의역이 시그마필드이며 (2) 확률의공리1-3을 만족하므로 확률이라 주장할 수 있다.

`#`

------------------------------------------------------------------------

`# 예제2` -- $|\Omega| = \aleph_1$ 인 경우, 확률정의 불가능

$\Omega=[0,1)$ 라고 하자. 이때 $2^\Omega$는 $\Omega$의 모든 부분집합들의 집합이다. 여기에서 $2^\Omega$는 시그마필드의 정의를 만족하므로 $(\Omega, 2^{\Omega})$ 는 잴 수 있는 공간이 된다. 이 공간위에서 함수 $\mathbb{P}: 2^{\Omega} \to [0,1]$ 를 아래와 같이 정의하자.

$$\mathbb{P}(A)=\lambda(A), \quad \text{$\lambda$ is lebesgue measure}.$$

이러한 함수 $\mathbb{P}$ 는 (1) 정의역이 시그마필드이지만 (2) 확률의공리1-3을 만족하지 않는다. (왜? 비탈리집합!) 따라서 함수 $\mathbb{P}$ 를 확률이라고 주장할 수 없다. 또한 $\mathbb{P}(A)=\lambda(A)$가 아닌 그 어떠한 방식으로 정의해도 잴 수 있는 공간 $(\Omega, 2^{\Omega})$ 위에서 확률을 무모순으로 정의하는게 불가능함이 밝혀져 있다.

`#`

------------------------------------------------------------------------

> 의문: 그러면 이름이 이상한것 아니야? 즉, $\Omega=[0,1)$ 일경우 $(\Omega, 2^{\Omega})$를 잴 수 있는 공간이라고 말하는 것 자체가 잘못된것 아니야??

------------------------------------------------------------------------

`# 예제3` -- $|\Omega| = \aleph_1$ 인 경우, 측도정의가능

$\Omega=[0,1)$ 라고 하자. 이때 $2^\Omega$는 $\Omega$의 모든 부분집합들의 집합이다. 여기에서 $2^\Omega$는 시그마필드의 정의를 만족하므로 $(\Omega, 2^{\Omega})$ 는 잴 수 있는 공간이 된다. 이 공간위에서 함수 $m: 2^{\Omega} \to [0,\infty]$ 를 아래와 같이 정의하자.

$$m(A)=0, \quad \forall A \in 2^{\Omega}$$

이러한 함수 $m$ 은 (1) 정의역이 시그마필드이고 (2) 측도의공리1-3을 만족한다. 따라서 함수 $m$를 측도라고 주장할 수 있다. (이러한 측도를 [trivial measure](https://en.wikipedia.org/wiki/Trivial_measure)라고 함)

`#`

------------------------------------------------------------------------

`-` 요약

-   사실1: 확률을 정의하기 위해서는 잴 수 있는 공간 $(\Omega, {\cal F})$ 이 전제되어야 하지만, 잴 수 있는 공간 $(\Omega, {\cal F})$ 가 잘 정의되었다고 해서 항상 확률을 정의할 수 있는건 아니다.
-   사실2: 모든 잴 수 있는 공간 $(\Omega, {\cal F})$ 에는 그 공간에서 정의가능한 측도가 반드시 하나는 존재한다. 그렇지만 존재하는 그 측도가 확률측도라는 보장은 없다. (즉 무슨 수를 쓰든 확률을 무모순으로 정의하는 것이 불가능한 잴 수 있는 공간 $(\Omega, {\cal F})$ 이 존재할 수 있다)

`# 정의` -- 잴 수 있는 공간 $(\Omega,{\cal F})$ 와 그 공간에서의 측도 $m:{\cal F} \to [0,\infty]$ 을 묶은 $(\Omega, {\cal F},m)$ 을 measure space 라고 한다. 만약에 측도 $m$이 확률측도의 정의를 만족한다면 공간 $(\Omega, {\cal F},m)$ 혹은 $(\Omega, {\cal F},\mathbb{P})$ 는 확률공간 (probability space) 라고 한다.

------------------------------------------------------------------------

### 르벡메저는 어디에서 정의할까?

`# 확장이론` $\Omega=[0,1)$ 일 경우 길이를 정의하는 방법:

-   사전인지사항1: $(\Omega, 2^{\Omega})$ 에서 길이를 정의하는 것은 불가능함
-   사전인지사항2: $(\Omega, \{\emptyset, \Omega\})$ 에서 $\lambda$를 정의하는 것은 의미가 없음.
-   문제를 해결하는 자세: $\{\emptyset, \Omega\}$ 보다는 크고, $2^{\Omega}$ 보다는 작은 어떠한 ${\cal F}$에 대하여 길이를 정의해야 하지 않나?
-   즉 $(\Omega, ???, \lambda)$ 를 measure space 로 만드는 적당한 시그마필드 $???$ 를 찾으면 되는것 아닌가? 그리고 그 $???$ 에서 길이를 정의하면 되지 않나?

우리는

1.  $(\Omega, ???, \lambda)$ 를 measure space 로 만드는 시그마필드는 찾는 방법??
2.  $???$ 에서 길이를 정의하는 방법??

을 논의하면 된다.

`#`

------------------------------------------------------------------------

$(\Omega, ???, \lambda)$ 를 measure space 로 만드는 시그마필드는 찾는 방법?? 을 생각하자. 가능한 방식은 아래의 2가지가 있는데

`방법1`: $2^\Omega$ 에서 길이를 잴 수 없는 집합들을 제외한다.

`방법2`: 길이를 정의할 수 있는 집합들 ${\cal A}$를 정의하고 이를 확장시킨다.

이중에서 방법2를 채택한다.

------------------------------------------------------------------------

`# 복습예제` -- ${\cal F}$를 구하는 것은 귀찮은 일이었지..

$\Omega=\{1,2,3,4\}$이라고 하자. 내가 관심있는 event의 모음은 아래와 같다.

$${\cal A} = \{\{1\},\{2\}\}$$

당연히 이러한 이벤트에 대해서만 적절한 길이를 정의하면 좋겠는데, 이는 불가능 하다. 왜냐하면 ${\cal A}$는 시그마필드가 아니기 때문이다. 따라서 할 수 없이 아래와 같은 방식으로 시그마필드를 구해야 했다.

$${\cal F} = \big\{\emptyset, \{1\}, \{2\}, \{1,2\}, \{3,4\}, \{1,3,4\}, \{2,3,4\}, \Omega \big\}$$

이러한 ${\cal F}$를 구하기는 것은 귀찮은 일인데, 이를 편리하게 해결하기 위해서 $\sigma({\cal A})$라는 기호를 도입하고 이를 "$\{1\}$, $\{2\}$를 원소로 가지는 최소한의 ${\cal F}$" 라고 생각 하기로 하였다.

------------------------------------------------------------------------

`걱정`: 문제는 이러한 논리전개가 항상 가능하냐는 것이다. 즉 임의의 ${\cal A}$에 대해서 $\sigma({\cal A})$라는 집합이 항상 잘 정의되냐는 것이다.

> `확장이론1`: 걱정할 필요 없다. 언제나 $\sigma({\cal A})$라는 표현은 가능하다. 즉 $\Omega$의 임의의 부분집합에 대하여 우리가 관심있는 집합만 모은 것을 ${\cal A}$라고 할때, ${\cal A}$의 모든 원소를 포함하고 시그마필드의 정의를 만족하는 최소한의 시그마필드 $\sigma({\cal A})$는 항상 존재한다.

`#`

------------------------------------------------------------------------

`# 예제2`

$\Omega = \mathbb{R}$ 이라고 하자. 이중에서 우리가 관심있는 집합들은 르벡메져로 길이를 명확하게 잴 수 있는 아래와 같은 형태이다.

$$[a,b]$$

여기에서 $a,b \in \mathbb{R}$, $a<b$ 이라고 하자. 따라서 이 경우 ${\cal A}$를 아래와 같이 설정할 수 있다.

$${\cal A} = \big\{[a,b]: a,b \in \mathbb{R}, a<b\big\}$$

이제 $\sigma({\cal A}):={\cal R}$ 를 상상하자. (확장이론1에 의하면 이러한 ${\cal R}$ 는 항상 존재함)

------------------------------------------------------------------------

언뜻 생각하면 ${\cal R}$의 원소는 $[a,b]$ 의 형태만 가능하여, 확률 혹은 길이를 정의함에 너무 제한적인 정의역일것 같은데 그렇지 않다. ${\cal R}$ 은 상당히 많은 케이스를 포함하는 집합이다. 예를들면 아래와 같은 집합들은 모두 ${\cal R}$ 의 원소이다.

-   $[0,2)$
-   $\{2\}$
-   $(0,2)$
-   $[0,\infty)$, $(0,\infty)$
-   $(-\infty,0)$, $(-\infty,0]$
-   $[1,2] \cup [3,4]$
-   $(1,2] \cup [3,4)$
-   $\mathbb{N}$, $\mathbb{Z}$, $\mathbb{Q}$
-   $[0,2] \cap \mathbb{Q}$

`#`

------------------------------------------------------------------------

`# 예제3` -- motivating EX

$\Omega=\{1,2,3,4\}$이라고 하자. 내가 관심있는 집합의 모음은 아래와 같다.

$${\cal A} = \{\emptyset, \{1\},\{2\},\{3,4\},\Omega\}$$

여기에서 ${\cal A}$는 시그마필드가 아니다. 따라서 ${\cal A}$에서는 확률을 정의할 수 없다. 확률을 정의하려면 $\sigma({\cal A})$에서 정의해야 한다.

`-` 소망: 그래도 그냥 ${\cal A}$에서만 확률 비슷한걸[^2] 잘 정의하면 안될까?

[^2]: 정의역이 시그마필드가 아니므로 확률이라고 말할 수 없다

------------------------------------------------------------------------

`-` 희망: 이게 될 것 같다. 예를들면 함수 $\tilde{P}:{\cal A} \to [0,1]$를 아래와 같이 정의하자.

-   $\tilde{P}(\emptyset) = 0$
-   $\tilde{P}(\{1\}) = 1/4$
-   $\tilde{P}(\{2\}) = 1/2$
-   $\tilde{P}(\{3,4\}) = 1/4$
-   $\tilde{P}(\Omega) = 1$

이 정도만 정의해보자. $\tilde{P}$는 정의역이 시그마필드가 아니라는 점만 제외하면 set function $\tilde{P}$ 는 확률의 공리 1,2,3을 따른다. 이렇게 함수 $\tilde{P}$를 정의하게 되면

$$\sigma({\cal A}) = \big\{\emptyset, \{1\}, \{2\}, \{1,2\}, \{3,4\}, \{1,3,4\}, \{2,3,4\}, \Omega \big\}$$

에서의 확률 $\mathbb{P}:\sigma({\cal A}) \to [0,1]$는 확률 비슷한 함수 $\tilde{P}$를 "알아서, 잘, 센스있게" 확장하여 정의할 수 있다.

------------------------------------------------------------------------

구체적으로는 아래와 같이 된다.

|   정의역    | $\mathbb{P}$  |  $\tilde{P}$  |
|:-----------:|:-------------:|:-------------:|
| $\emptyset$ |      $0$      |      $0$      |
|   $\{1\}$   | $\frac{1}{4}$ | $\frac{1}{4}$ |
|   $\{2\}$   | $\frac{1}{2}$ | $\frac{1}{2}$ |
|  $\{3,4\}$  | $\frac{1}{4}$ | $\frac{1}{4}$ |
|  $\Omega$   |      $1$      |      $1$      |
|     $-$     |      $-$      |      $-$      |
|  $\{1,2\}$  | $\frac{3}{4}$ |     None      |
| $\{1,3,4\}$ | $\frac{1}{2}$ |     None      |
| $\{2,3,4\}$ | $\frac{3}{4}$ |     None      |

`#`

------------------------------------------------------------------------

`# 예제4` -- motivating EX (2)

$\Omega=\{1,2,3,4\}$이라고 하고 ${\cal A} = \{\emptyset, \{1\},\{2\}, \{3,4\}, \Omega\}$ 라고 하자. 그리고 아래와 같은 $\sigma({\cal A})$를 다시 상상하자.

$$\sigma({\cal A}) = \big\{\emptyset, \{1\}, \{2\}, \{1,2\}, \{3,4\}, \{1,3,4\}, \{2,3,4\}, \Omega \big\}$$

위의 시그마필드에서 확률을 예제3과 다른 방식으로 정의할 수 도 있다.

------------------------------------------------------------------------

예를들면 아래와 같은 방식으로 정의가능하다.

|   정의역    | $\mathbb{P}_1$ | $\tilde{P}_1$ |
|:-----------:|:--------------:|:-------------:|
| $\emptyset$ |      $0$       |      $0$      |
|   $\{1\}$   | $\frac{1}{3}$  | $\frac{1}{3}$ |
|   $\{2\}$   | $\frac{1}{3}$  | $\frac{1}{3}$ |
|  $\{3,4\}$  | $\frac{1}{3}$  | $\frac{1}{3}$ |
|  $\Omega$   |      $1$       |      $1$      |
|     $-$     |      $-$       |      $-$      |
|  $\{1,2\}$  | $\frac{2}{3}$  |     None      |
| $\{1,3,4\}$ | $\frac{2}{3}$  |     None      |
| $\{2,3,4\}$ | $\frac{2}{3}$  |     None      |

------------------------------------------------------------------------

또한 아래와 같은 방식도 가능하다.

|   정의역    | $\mathbb{P}_2$ | $\tilde{P}_2$ |
|:-----------:|:--------------:|:-------------:|
| $\emptyset$ |      $0$       |      $0$      |
|   $\{1\}$   |      $0$       |      $0$      |
|   $\{2\}$   |      $0$       |      $0$      |
|  $\{3,4\}$  |      $1$       |      $1$      |
|  $\Omega$   |      $1$       |      $1$      |
|     $-$     |      $-$       |      $-$      |
|  $\{1,2\}$  |      $0$       |     None      |
| $\{1,3,4\}$ |      $1$       |     None      |
| $\{2,3,4\}$ |      $1$       |     None      |

------------------------------------------------------------------------

어떠한 방식으로 정의하든 ${\cal A}$에서 확률 비슷한 것 $\tilde{P}_1,\tilde{P}_2$를 잘 정의하기만 $\sigma({\cal A})$에서의 확률로 적절하게 확장할 수 있다. 심지어 이런 확장은 유일한 듯 하다.

> `확장이론2`: **운이 좋다면**, ${\cal A}$ 에서 확률의 공리를 만족하는 적당한 함수 $\tilde{P}:{\cal A} \to [0,1]$를 $(\Omega, \sigma({\cal A}))$ 에서의 확률측도 $\mathbb{P}$로 업그레이드 할 수 있으며 업그레이드 결과는 유일하다.

`#`

------------------------------------------------------------------------

`# 예제5` -- 운이 안 좋은 경우 1

$\Omega=\{1,2,3\}$ 이라고 하고 ${\cal A} = \{\emptyset, \{1,2\},\{2,3\}, \Omega\}$ 라고 하자.

아래와 같은 확률 비슷한 함수 $\tilde{P}:{\cal A} \to [0,1]$를 정의하자.

-   $\tilde{P}(\emptyset) = 0$
-   $\tilde{P}(\{1,2\}) = 0$
-   $\tilde{P}(\{2,3\}) = 0$
-   $\tilde{P}(\Omega) = 1$

$\tilde{P}$는 분명히 ${\cal A}$에서 확률의 공리1-3을 만족한다. 하지만 $\sigma({\cal A})$로의 확장은 불가능하다.

`#`

------------------------------------------------------------------------

`# 예제6` -- 운이 안 좋은 경우 2

$\Omega=\{1,2,3,4\}$ 이라고 하고 ${\cal A} = \{\emptyset, \{1,2\},\{2,3\}, \Omega\}$ 라고 하자.

아래와 같은 확률 비슷한 함수 $\tilde{P}:{\cal A} \to [0,1]$를 정의하자.

-   $\tilde{P}(\emptyset) = 0$
-   $\tilde{P}(\{1,2\}) = 1/2$
-   $\tilde{P}(\{2,3\}) = 1/2$
-   $\tilde{P}(\Omega) = 1$

$\tilde{P}$는 분명히 ${\cal A}$에서 확률의 공리1-3을 만족한다. $\sigma({\cal A})$로의 확장도 가능하다. 하지만 유일한 확장을 보장하지 않는다.

------------------------------------------------------------------------

::::: columns
::: {.column width="50%"}
|   정의역    | $\mathbb{P}_1$ | $\mathbb{P}_2$ |  $\tilde{P}$  |
|:-----------:|:--------------:|:--------------:|:-------------:|
| $\emptyset$ |      $0$       |      $0$       |      $0$      |
|  $\{1,2\}$  | $\frac{1}{2}$  | $\frac{1}{2}$  | $\frac{1}{2}$ |
|  $\{2,3\}$  | $\frac{1}{2}$  | $\frac{1}{2}$  | $\frac{1}{2}$ |
|  $\Omega$   |      $1$       |      $1$       |      $1$      |
:::

::: {.column width="50%"}
|   정의역    | $\mathbb{P}_1$ | $\mathbb{P}_2$ | $\tilde{P}$ |
|:-----------:|:--------------:|:--------------:|:-----------:|
|   $\{1\}$   |      $0$       | $\frac{1}{2}$  |    None     |
|   $\{2\}$   | $\frac{1}{2}$  |      $0$       |    None     |
|   $\{3\}$   |      $0$       | $\frac{1}{2}$  |    None     |
|   $\{4\}$   | $\frac{1}{2}$  |      $0$       |    None     |
|  $\{1,3\}$  |      $0$       |      $1$       |    None     |
|  $\{1,4\}$  | $\frac{1}{2}$  | $\frac{1}{2}$  |    None     |
|  $\{2,4\}$  |      $1$       |      $0$       |    None     |
|  $\{3,4\}$  | $\frac{1}{2}$  | $\frac{1}{2}$  |    None     |
| $\{2,3,4\}$ |      $1$       | $\frac{1}{2}$  |    None     |
| $\{1,3,4\}$ | $\frac{1}{2}$  |      $1$       |    None     |
| $\{1,2,4\}$ |      $1$       | $\frac{1}{2}$  |    None     |
| $\{1,2,3\}$ | $\frac{1}{2}$  |      $1$       |    None     |
:::
:::::

`#`

------------------------------------------------------------------------

`# 예제7` -- 혹시...

$\Omega=\mathbb{R}$, ${\cal A}=\big\{[a,b]: a,b \in \mathbb{R}, a<b \big\}$ 라고 하자. ${\cal A}$에서만 측도비슷한 함수 $\tilde{\lambda}([a,b])=b-a$를 잘 정의한다면 그것이 $\sigma({\cal A})$에서의 측도 $\lambda$으로 업그레이드 가능하며, 그 업그레이드 결과는 유일할까? 그래서 아래의 집합들에 대한 확률을 무모순으로 정의가능할까?

-   $\{2\}$, $\{0\}$, $\dots$
-   $(0,2)$, $[0,2)$, $(0,2]$, $\dots$
-   $[0,\infty)$, $(0,\infty)$, $(-\infty,0)$, $(-\infty,0]$, $\dots$
-   $(1,2] \cup [3,4)$, $(1,2) \cup (3,4]$, $\dots$
-   $\mathbb{N}$, $\mathbb{Z}$, $\mathbb{Q}$, $[0,2] \cap \mathbb{Q}$, $\dots$

> 이게 가능하다면 대박인데, 결론적으로 말하면 이게 가능하다. 이게 가능한 이유는 카라테오도리의 확장정리 때문

`#`

------------------------------------------------------------------------

### 측도론의 유산

`# 이론` -- 아래와 같은 집합을 고려하자.

-   ${\cal A}_1:= \{A\subset \mathbb{R}: A \text{ is open}\}$[^3]
-   ${\cal A}_2:= \{(a,b): a,b \in \mathbb{R}, a<b\}$
-   ${\cal A}_3:= \{[a,b): a,b \in \mathbb{R}, a<b\}$
-   ${\cal A}_4:= \{(a,b]: a,b \in \mathbb{R}, a<b\}$
-   ${\cal A}_5:= \{[a,b]: a,b \in \mathbb{R}, a<b\}$
-   ${\cal A}_6:= \{(-\infty,b): a,b \in \mathbb{R}, a<b\}$
-   ${\cal A}_7:= \{(-\infty,b]: a,b \in \mathbb{R}, a<b\}$
-   ${\cal A}_8:= \{(a,\infty): a,b \in \mathbb{R}, a<b\}$
-   ${\cal A}_9:= \{[a,\infty): a,b \in \mathbb{R}, a<b\}$

[^3]: 여기에서 open은 엄밀하게 말하면 usual topological spcace $(\mathbb{R},{\cal U})$ 에서의 ${\cal U}$-open set을 의미한다. 즉 보통위상공간에서 정의가능한 openset을 의미한다.

------------------------------------------------------------------------

아래가 성립한다.

$${\cal R}:={\cal B}(\mathbb{R}) = \sigma({\cal A}_1)=\sigma({\cal A}_2)=\dots=\sigma({\cal A}_9)$$

`#`

------------------------------------------------------------------------

`# 정의` -- 위의 이론에서 논의된 ${\cal R}$을 보렐시그마필드라고 한다.

> 참고로 "시그마필드"는 "잴 수 있는 집합들의 모임" 이지만, "보렐시그마필드"는 "합리적인 길이를 잴 수 있는 집합들의 모임" 이다. 그리고 보렐시그마필드야 말로 $(\mathbb{R},???,\lambda)$ 를 measure space로 만드는 가장 합리적인 집합(collection)이다.

`#`

------------------------------------------------------------------------

`# 이론` -- $\Omega=\mathbb{R}$ 에 대하여 아래와 같은 collection ${\cal A}$를 고려하자.

$${\cal A}=\{(a,b]: a,b\in \mathbb{R}, a<b\}$$

그리고 아래와 같은 함수 $\tilde{\lambda}:{\cal A} \to [0,\infty]$을 고려하자.

$$\tilde{\lambda}((a,b]) = b-a$$

이러한 함수 $\tilde{\lambda}$은 $(\mathbb{R},{\cal R})$에서의 메져 $\lambda:{\cal R} \to [0,\infty]$로 쉽게 업그레이드 가능하며 이 업그레이드 결과는 유일하다.

`#`

`# 정의` -- 위의 이론에 의하여 업그레이드 된 메져 $\lambda$을 르벡메져라고 한다.