---
title: 08wk - 측도론의 중요이론들 (2)
author: 최규빈
date: 10/15/2025
---

### 강의영상

<!-- {{<video https://youtu.be/playlist?list=PLQqh36zP38-y6Y6YRnbfACyYa247BLvtc&si=nsj2yJTWqgj6mIMB >}} -->

---

### 딘킨의 $\pi-\lambda$ theorem

`# 이론` -- Dynkin's $\pi-\lambda$ theorem ($\star$)

${\cal P} \subset 2^{\Omega}$가 파이시스템이면 $l({\cal P})=\sigma({\cal P})$이다. 

> Note: ${\cal P}$를 포함하는 최소한의 시그마필드를 찾기 위해서는 ${\cal P}$를 포함하는 최소한의 람다시스템만 찾아도 충분하다는 의미이다. 

`#`

---

(증명)

아래를 보이는 것이 목표이다. 

> **(a)** $l({\cal P})=\sigma({\cal P})$ 

이를 위해서는 아래를 보이면 충분하다. 

> **(b)** $l(\cal P) \subset \sigma({\cal P})$ and $l(\cal P) \supset \sigma({\cal P})$. 

그런데 $l(\cal P) \subset \sigma({\cal P})$ 은 당연하므로^[$l({\cal P})$는 1차확장상태이고 $\sigma({\cal P})$는 2차확장상태잖아요..?] 우리는 아래를 보이면 충분하다. 

> **(c)** $l({\cal P}) \supset \sigma({\cal P})$


---


그런데 만약 $l({\cal P})$ 가 시그마필드라면 $\sigma({\cal P})$의 정의에 의하여 (c)가 성립하므로 우리는 아래를 보이면 충분하다. 

> **(d)** $l({\cal P})$ is $\sigma$-field 

그런데 만약 $l({\cal P})$ 은 이미 람다시스템이므로 $l({\cal P})$가 추가적으로 파이시스템임을 보인다면 $l({\cal P})$를 시그마필드라고 주장할 수 있다. 따라서 우리는 아래가 성립함을 보이면 충분하다. 

> **(e)** $l({\cal P})$ is $\pi$-system 

${\cal D}_E = \{F: E\cap F \in l({\cal P}), ~F \in l({\cal P})\}$ 라고 정의할 때 $\forall E \in l({\cal P}): ~ {\cal D}_E = l({\cal P})$ 를 보이면, $l({\cal P})$ 이 파이시스템을 보이는 것이 된다. 즉 아래를 보이면 된다. 

> **(e)** $\forall E \in l({\cal P}): ~ {\cal D}_E = l({\cal P})$. 

---

이를 위해서는 다시 아래를 보이면 충분하다. 

> **(f)** $\forall E \in l({\cal P}): ~ {\cal D}_E \subset l({\cal P})$ and $l({\cal P}) \subset {\cal D}_E$

그런데 ${\cal D}_E \subset l({\cal P})$ 는 당연하므로^[애초에 ${\cal D}_E$ 자체가 $l({\cal P})$ 의 원소들중에서 특정조건을 만족하는애들만 고려하는거잖아요?] 아래를 보여도 충분하다. 

> **(g)** $\forall E \in l({\cal P}): ~ l({\cal P}) \subset {\cal D}_E$

그런데 임의의 $E \in l({\cal P})$에 대하여 ${\cal D}_E$가 ${\cal P}$를 포함하는 람다시스템이라면, $l({\cal P})$의 정의에 의하여 (g)가 성립하므로 아래를 보이면된다. 

> **(h)** $\forall E \in l({\cal P}):$ (1) $\Omega \in {\cal D}_E$ (2) ${\cal D}_E$ is $^c$-closed (3) ${\cal D}_E$ is $\uplus$-closed. <br/> **(i)** $\forall E \in l({\cal P}): {\cal P} \subset {\cal D}_E$.

--- 

$F \in {\cal D}_E \Leftrightarrow \big( F \in l({\cal P}) \text{ and } E \cap F \in l({\cal P}) \big)$ 임을 이용하여 "(h) 임의의 $E \in l({\cal P})$에 대해서 ${\cal D}_E$가 람다시스템"임을 체크해보자. 

(세부증명1)

1. 생각을 편하게 하기 위해서 $E \in l({\cal P})$를 고정하자. [$\Omega \in {\cal D}_E$는 성립한다. 왜냐하면 $\Omega$는 $E$를 완전히 포함하므로.] 이때 [...]의 논리가 임의의 $E \in l({\cal P})$에 대해서도 성립하므로 모든 $E$에 대하여 ${\cal D}_E$는 전체집합을 포함함을 보일 수 있다. 

---

2. 생각을 편하게 하기 위해서 $E \in l({\cal P})$를 고정하자. [람다시스템의 두번째 조건 "여집합에 닫혀있음"은 "포함관계에 있는 차집합에 닫혀있음"으로 바꿀 수 있으므로 그걸 체크해보자. <$A \subset B$을 만족하는 ${\cal D}_E$의 두 원소 $A,B$를 뽑자. 우리는 $B-A$가 ${\cal D}_E$의 원소임을 보이면된다. 즉 $(B-A) \cap E \in l({\cal P})$임을 보이면된다. 그런데 (벤다이어그램을 그려보면) $(B-A)\cap E  = (B\cap E) - (A \cap E)$ 임을 알 수 있다. $B\cap E$, $A\cap E$, $(B\cap E) - (A\cap E)$가 각각 $l({\cal P})$의 원소이므로 $B-A \in {\cal D}_E$ 임을 보일 수 있다.> 이때 <...>의 논리가 $A\subset B$를 만족하는 ${\cal D}_E$의 임의의 두 원소에 대해서 성립하므로 고정된 $E$에 대해서 ${\cal D}_E$는 포함관계에 있는 차집합 연산에 닫혀있다고 볼 수 있다.] 이때 [...]의 논리가 임의의 $E \in l({\cal P})$에 대해서도 성립하므로 모든 $E$에 대하여 ${\cal D}_E$는 포함관계에 있는 차집합연산에 닫혀있음을 보일 수 있다. 

---

3. 생각을 편하게 하기 위해서 $E \in l({\cal P})$를 고정하자. [${\cal D}_E$가 $\uplus$-closed임을 보이면 된다. <${\cal D}_E$에서 서로소인 무한집합열 $B_1,B_2,\dots$을 선택하여 고정하자. 우리는 $(\uplus_{n=1}^{\infty} B_n\big) \cap E \in l({\cal P})$임을 보이면 된다. 그런데 모든 $n$에 대하여 $B_n \cap E \in l(P)$이므로 $\uplus_{n=1}^{\infty} B_n \in {\cal D}_E$를 보일 수 있다.> 그런데 <...>의 논의는 임의의 $B_1,B_2,\dots$에 대해서 모두 성립하므로 ${\cal D}_E$는 고정된 $E$에 대하여 $\uplus$-closed임을 알 수 있다.] 그런데 [...]의 논의는 임의의 $E$에 대하여 성립하므로 ${\cal D}_E$는 임의의 $E$에 대하여 $\uplus$-closed임을 알 수 있다. 

따라서 ${\cal D}_E$는 람다시스템이다

(세부증명1끝)

---

이제 "(i) 임의의 $E \in l({\cal P})$에 대하여 ${\cal P} \subset {\cal D}_E$"임을 보이자. 

(세부증명2)

먼저 아래의 사실을 증명하자. 

`# claim` -- 세부증명2를 위한 우리의 무기
$$X \in {\cal P} \Rightarrow {\cal P} \subset {\cal D}_X$$

proof. $X \in {\cal P}$ 가 주어진 상황에서 ${\cal P}$의 임의의 원소는 "(1) $l(P)$의 원소이고 (2) $X$와 교지합연산한 결과가 $l(P)$의 원소임"을 만족한다. 조건1-2는 ${\cal D}_X$의 원소일 조건이므로 $X \in {\cal P} \Rightarrow {\cal P} \subset {\cal D}_X$가 증명되었다. 

`#` 

---

이제 $\forall E \in l({\cal P}): {\cal P} \subset {\cal D}_E$을 보이자. 편의상 $E \in l({\cal P})$를 고정하자. [${\cal P} \subset {\cal D}_E$ 임을 보이기 위해서는 $\forall X \in {\cal P}: X \in {\cal D}_E$ 임을 보여야 한다. 우리의 무기에 의하여 $X \in {\cal P} \Rightarrow {\cal P} \subset {\cal D}_X$ 임을 쓸 수 있다. 그런데 ${\cal D}_X$는 (h)에 의하여 람다시스템이되므로 (따라서 ${\cal D}_X$는 졸지에 ${\cal P}$를 포함하는 람다시스템이 되었음) 아래가 성립한다. 

$$X \in {\cal P} \Rightarrow l({\cal P}) \subset {\cal D}_X$$

그런데 "$l({\cal P}) \subset {\cal D}_X$" 이 의미하는건 $l({\cal P})$의 임의의 원소는 ${\cal D}_X$에 속한다는 의미이므로 $E \in {\cal D}_X$ 가 만족한다. 따라서 $E \cap X \in l({\cal P})$가 만족한다. 정리하면 아래가 만족한다. 

$$X \in {\cal P} \Rightarrow E \cap X \in l({\cal P})$$ 따라서 ${\cal P}$의 모든원소는 $l({\cal P})$의 원소이고 $E$와 교집합연산을 하였을때 그 결과가 $l({\cal P})$에 속한다. 즉 ${\cal P}$의 모든 원소는 ${\cal D}_E$의 정의를 만족한다. 따라서 $${\cal P} \subset {\cal D}_E$$] 이때 [...]의 논의가 임의의 $E \in l({\cal P})$에 대하여 성립하므로 증명끝.